### PR TITLE
Update CorpFfaPlugin.java

### PR DESCRIPTION
**Pull request by Veracs**
Added the Emberlight to the immutable list of arclight weapons.

### CODE REVIEW

**Comment by Box-Of-Hats** [comment]
This looks good. Do you know if the emberlight spec uses the same animation ID as the arclight?

**Comment by Veracs** [comment]
@Box-Of-Hats Hi Jake. Thanks for looking over that change. I’m not 100% versed in Java, or how the plugin is structured, but that immutable list, as well as the animation are all that appeared like they needed updated.

To answer your question, it is a slightly different animation, however I do not know the animation ID. Is there a way I could get this for you? I’d be happy to add it in as well

**Comment by Veracs** [comment]
@Box-Of-Hats Emberlight spec animation ID is 11138 according to RuneLite.

**Review by Box-Of-Hats — CHANGES_REQUESTED** [review]
Thanks for getting that ID :) Can you add that animation ID to the check on line 405? It should work as expected once that's been added

**Comment by Veracs** [comment]
@Box-Of-Hats Line 405 updated. Could you just verify that I put the correct syntax? As I said before, not super well-versed in Java. I just tried to add it as an OR statement. Wasn't sure if I needed to put parenthesis around the first and second animID's.

My change: `animId == #### || animId == 11138 && allowArclight()`

Example I'm talking about with parenthesis: `If ((animId == #### || animId == 11138) && allowArclight())`

**Comment by Box-Of-Hats** [comment]
@Veracs Yes, it needs the parenthesis like you've got in your example

**Comment by Veracs** [comment]
@Box-Of-Hats Done. :)

**Review by Box-Of-Hats — APPROVED** [review]

**Pull request merged**
